export const LOADING='LOADING'
// get all products

export const GET_ALL_PRODUCTS_SUCCESS='GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAILED='GET_ALL_PRODUCTS_FAILED'

//add prod
export const ADD_PRODUCT_SUCCESS='ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILED='ADD_PRODUCT_FAILED'
// get prod details

export const GETONE_PRODUCT_SUCCESS='GETONE_PRODUCT_SUCCESS'
export const GETONE_PRODUCT_FAILED='GETONE_PRODUCT_FAILED'

//edit product
export const EDIT_PRODUCT_SUCCESS='EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_FAILED='EDIT_PRODUCT_FAILED'
//delet product
export const DELET_PRODUCT_SUCCESS='DELET_PRODUCT_SUCCESS'
export const DELET_PRODUCT_FAILED='DELET_PRODUCT_FAILED'